### ISSUE TITLE
please drop database and remove this issue.

### ISSUE THREAD

**Issue by yadimon** [AMOSTeam3/amos-ss15-proj3#158]
our DB doesnt work anymore. Cant drop it from here.
i think over cource console, you can reset it.
(need schema traceability! or modify hibernate.cfg.xml)

**Comment by TPolzer** [comment]
Do we have an easy way to recreate the database after dropping?

And what did you do to wreck it so completely??

**Comment by td5r** [comment]
O.o ... is nothing more working?
I started the app and clicked on configure and it doesn't response anymore ^^

**Comment by TPolzer** [comment]
The database does not respond anymore to most queries.

**Comment by gayathery** [comment]
Hold on let me check what is the problem

**Comment by gayathery** [comment]
The database hangs couple of times . What i could see quickly is some one created a new table and all over the main requirement table and its mappings the data is corrupt.

**Comment by TPolzer** [comment]
There were several open hanging transactions, the data is actually fine. I killed all the transactions, now it works again.

**Comment by gayathery** [comment]
I have deleted the corrupt data by the way.

**Comment by TPolzer** [comment]
By corrupt data you mean the requirements with null and -1 attributes? They have been there for about 1 week.

Edit: And the null fields will occur again after adding linkage to unknown requirements.

**Comment by gayathery** [comment]
So why is this last minute major changes happening now

**Comment by TPolzer** [comment]
To fulfill user story 49 I guess...
